services:
  db:
    image: postgres:14
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DATABASE_URL=postgresql://postgres:password@db:5432/app_development
      - TZ=Asia/Tokyo
      - RAILS_LIVE_RELOAD_ENABLED=true
      - RAILS_LIVE_RELOAD_HOST=0.0.0.0
    depends_on:
      - db
volumes:
  bundle:
  postgresql_data:
  node_modules:
